---
title: "DB Corp Model Clean"
author: "Andrew"
date: "July 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Rblpapi)
library(ggplot2)
library(stats)
library(quantmod)
library(zoo)
library(pls)
library(dplyr)
library(roll)
library(broom)
library(lubridate)
library(PerformanceAnalytics)
con<- blpConnect()
```
```{r}
#Create Bloomberg function to quickly retrieve data. Ticker = Bloomberg ticker, variable = Bloomberg data field, start = start date of data, days = whether to include non-trading days
bloom<- function(ticker,variable,start,days){
  result<- bdh(securities = ticker,
               fields = variable,
               start.date = start,
               include.non.trading.days = days)
  return(result)
}
```

```{r}
start_date <- as.Date("2004-01-02")
non_trade <- "FALSE"
```

```{r}
# Use the created bloom function to load the CBOE Oil ETF VIX Index and convert to an xts object
ovx<- bloom("OVX INDEX", "PX_LAST", start_date, non_trade)
ovx_xts<- xts(ovx[,-1], order.by = ovx$date)
```

```{r}
corp_oas<- bdh(securities = "LUACOAS Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)
mbs_oas<- bdh(securities = "LUMSOAS Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

corp_dur<- bdh(securities = "LUACMD Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

a_oas<-  bdh(securities = "LCA1OAS Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

a_dur<- bdh(securities = "LCA1MD Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

bbb_oas<-  bdh(securities = "LCB1OAS Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

bbb_dur<- bdh(securities = "LCB1MD Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

cvix<- bdh(securities = "CVIX Index", 
           fields = "PX_LAST", 
           start.date = start_date, include.non.trading.days = non_trade)

vol<- bdh(securities = "VIX Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

wti_oil<- bdh(securities = "USCRWTIC Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

jpy_10<- bdh(securities = "GTJPY10YR Govt", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

us_10<- bdh(securities = "USGG10YR Index",
            fields = "PX_LAST",
            start.date = start_date,include.non.trading.days = non_trade)

nom_fx<- bdh(securities = "NMFXVOL Index",
            fields = "PX_LAST",
            start.date = start_date,include.non.trading.days = non_trade)

hy_oas<- bdh(securities = "LF98OAS Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)

spx_price_earnings<- bdh(securities = "SPX Index", 
           fields = "PE_RATIO", 
           start.date = start_date,include.non.trading.days = non_trade)

opt_db<- c("periodicitySelection" = "MONTHLY")
cfnai<- bdh(securities = "CFNAI Index", 
           fields = "PX_LAST", 
           start.date = as.Date("1989-05-31"),include.non.trading.days = non_trade, options = opt_db)

corp_oas_m<- bdh(securities = "LUACOAS Index", 
           fields = "PX_LAST", 
           start.date = as.Date("1989-06-30"),include.non.trading.days = non_trade, options = opt_db)

hy_oas_m<- bdh(securities = "LF98OAS Index", 
           fields = "PX_LAST", 
           start.date = as.Date("1989-06-30"),include.non.trading.days = non_trade, options = opt_db)

dxy_usd<- bdh(securities = "DXY Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade)
           length(dxy_usd$PX_LAST)
```           


```{r}
er_time<- c("periodicitySelection" = "MONTHLY")
long_er<- bdh(securities = "LD07ER Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade, options = er_time)

crv530<- bdh(securities = "USYC5Y30 Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade, options = er_time)

us_30yr<- bdh(securities = "USGG30YR Index", 
           fields = "PX_LAST", 
           start.date = start_date,include.non.trading.days = non_trade, options = er_time)

chi_fcon<- bdh(securities = "NFCIINDX Index", 
           fields = "PX_LAST", 
           start.date = as.Date("1989-06-30"),include.non.trading.days = non_trade, options = opt_db)

chi_adj<- bdh(securities = "NFCIADJ Index", 
           fields = "PX_LAST", 
           start.date = as.Date("1989-06-30"),include.non.trading.days = non_trade, options = opt_db)

bloom_fcon<- bdh(securities = "BFCIUS Index", 
           fields = "PX_LAST", 
           start.date = as.Date("1989-06-30"),include.non.trading.days = non_trade, options = opt_db)
```

```{r}
#Create xts objects from Bloomberg data
corp_oas_xts<- xts(corp_oas[,-1], order.by = corp_oas$date)
cvix_xts<- xts(cvix[,-1], order.by = cvix$date)
vol_xts<- xts(vol[,-1], order.by = vol$date)
jpy_10_xts<- xts(jpy_10[,-1], order.by = jpy_10$date)
us_10_xts<- xts(us_10[,-1], order.by = us_10$date)
```

```{r}
#Merge xts objects into one dataframe.  Create new window starting on 2007-05-10 to account for the first date of the ovx index
oas_df<- merge(corp_oas_xts, cvix_xts,vol_xts,jpy_10_xts,us_10_xts, ovx_xts)
oas_df_window<- window(oas_df["2007-05-10/"])
```

```{r}
#Check for NAs and either remove or carry last observation forward
oas_df_window<- na.locf(oas_df_window)
colSums(is.na(oas_df_window))
```


##BUILD DATAFRAME
```{r}
DB_CORP_DF<- corp_oas %>%
  right_join(cvix, by = "date", suffix = c("_oas","_cvix")) %>%
  right_join(vol, by = "date", suffix = c("_cvix", "_vix")) %>%
  right_join(wti_oil, by = "date", suffix = c("_vix", "_wti")) %>%
  right_join(jpy_10, by = "date", suffix = c("_wti", "_jpy")) %>%
  right_join(us_10, by = "date", suffix = c("_jpy", "_us10")) %>%
  right_join(hy_oas, by = "date", suffix = c("_us10", "_hyoas")) %>%
  right_join(nom_fx, by = "date", suffix = c("_hyoas", "_nomfx")) %>%
  right_join(corp_dur, by = "date", suffix = c("_nomfx", "_dur")) %>%
  na.locf()
```

```{r}
look_back<- 1012
```




##ADD VECTORS TO DATAFRAME
```{r}
DB_CORP_DF<- DB_CORP_DF %>%
  mutate(sd_cvix = roll_sd(PX_LAST_cvix,look_back)) %>%
  mutate(sd_vol = roll_sd(PX_LAST_vix,look_back)) %>%
  mutate(sd_wti = roll_sd(PX_LAST_wti, look_back)) %>%
  mutate(sd_nomfx = roll_sd(PX_LAST_nomfx,look_back)) %>%
  mutate(us_jpy_spread = PX_LAST_us10 - PX_LAST_jpy) %>%
  mutate(sma_cvix = roll_mean(PX_LAST_cvix,look_back)) %>%
  mutate(sma_vol = roll_mean(PX_LAST_vix,look_back)) %>%
  mutate(sma_nomfx = roll_mean(PX_LAST_nomfx,look_back)) %>%
  mutate(zscore_cvix = (PX_LAST_cvix - sma_cvix)/sd_cvix) %>%
  mutate(zscore_vol = (PX_LAST_vix - sma_vol)/sd_vol) %>%
  mutate(zscore_nomfx = (PX_LAST_nomfx - sma_nomfx)/sd_nomfx) %>%
  mutate(spread_per_dur = PX_LAST_oas *100/PX_LAST)
```

##DB CORPORATE MODEL
```{r}
DB_MODEL<- lm(PX_LAST_oas ~ zscore_cvix + zscore_vol + sd_wti + us_jpy_spread, data = DB_CORP_DF)
summary(DB_MODEL)
```

```{r}
DB_CORP_DF_PREDICT<- DB_CORP_DF %>%
  mutate(predicted_oas = predict(DB_MODEL,DB_CORP_DF)) %>%
  mutate(model_residual = PX_LAST_oas - predicted_oas)
```

```{r}
ggplot(DB_CORP_DF_PREDICT, aes(date)) + geom_line(aes(y=PX_LAST_oas), color = "red") + geom_line(aes(y = predicted_oas), color= "blue") + theme_minimal() + ggtitle("Actual IG OAS (red) vs DB Model Predicted OAS(blue)") + labs(y = "OAS") 
```

```{r}
ggplot(DB_CORP_DF_PREDICT, aes(date)) + geom_line(aes(y=spread_per_dur), color = "red") + theme_minimal() + ggtitle("Bloomberg Barclays Corporate Index Spread Per Unit of Duration") + labs(y = "Spread Per Unit of Duration") 
ggplot(DB_CORP_DF_PREDICT, aes(date)) + geom_line(aes(y=PX_LAST), color = "red") + theme_minimal() + ggtitle("Bloomberg Barclays Corporate Index Duration") + labs(y = "Mod. Adj. Duration") 
ggplot(DB_CORP_DF_PREDICT, aes(date)) + geom_line(aes(y=PX_LAST_oas), color = "red") + theme_minimal() + ggtitle("Bloomberg Barclays Corporate Index OAS") + labs(y = "Spread in %") 
```

```{r}
ggplot(DB_CORP_DF_PREDICT, aes(date)) + geom_line(aes(y=model_residual), color = "darkgreen") + theme_minimal() + ggtitle("Model Residual") + labs(y = "OAS")
```

```{r}
last(DB_CORP_DF_PREDICT$predicted_oas)
```

```{r}
boxplot(DB_CORP_DF_PREDICT$PX_LAST_oas, col = "wheat", horizontal = TRUE, main = "Corporate Sector OAS", sub = "red dash = current, green = mean", tick = TRUE, cex.axis = 0.5)
axis(1, at=seq(0.5,6.75,0.25), cex.axis = 0.5)
legend("topright", c("Current OAS", "Mean OAS"), fill = c("red", "green"))
abline(v = last(DB_CORP_DF_PREDICT$PX_LAST_oas), col = "red", lwd = 2, lty = 1)
abline(v = mean(DB_CORP_DF_PREDICT$PX_LAST_oas), col = "green", lwd = 2)
```

```{r}
boxplot(DB_CORP_DF_PREDICT$PX_LAST_vix, col = "wheat", horizontal = TRUE, main = "VIX Distribution", tick = TRUE, cex.axis = 0.5)
axis(1, at=seq(5,90,5), cex.axis = 0.5)
legend("topright", c("Current VIX", "Mean VIX"), fill = c("red", "green"))
abline(v = last(DB_CORP_DF_PREDICT$PX_LAST_vix), col = "red", lwd = 2, lty = 1)
abline(v = mean(DB_CORP_DF_PREDICT$PX_LAST_vix), col = "green", lwd = 2)

```

```{r}
boxplot(DB_CORP_DF_PREDICT$spread_per_dur, col = "wheat", horizontal = TRUE, main = "Corporate OAS per Year of Duration", tick = TRUE, cex.axis = 0.5)
axis(1, at=seq(5,110,5), cex.axis = 0.5)
legend("topright", c("Current OAS Per Year of Duration", "Mean OAS Per Year of Duration"), fill = c("red", "green"))
abline(v = last(DB_CORP_DF_PREDICT$spread_per_dur), col = "red", lwd = 2, lty = 1)
abline(v = mean(DB_CORP_DF_PREDICT$spread_per_dur), col = "green", lwd = 2)
```

```{r}
corp_group<- corp_oas %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  na.locf()
```

```{r}
corp_year<-ggplot(corp_group, aes(x = date, y = PX_LAST, color = "red")) + geom_line() + facet_wrap(~year, scales = "free")
corp_year
```
```{r}
db_xts<- xts(DB_CORP_DF_PREDICT[-1], order.by = DB_CORP_DF_PREDICT$date)
```

```{r}
chart.Boxplot(db_xts$PX_LAST_oas, xlab = "Spread in Percent", main = "Corporate Sector OAS")
abline(v = 0.1)
```
```{r}
xts_a_oas<- xts(a_oas$PX_LAST, order.by = a_oas$date)
xts_a_dur<- xts(a_dur$PX_LAST, order.by = a_dur$date)
xts_bbb_oas<- xts(bbb_oas$PX_LAST, order.by = bbb_oas$date)
xts_bbb_dur<- xts(bbb_dur$PX_LAST, order.by = bbb_dur$date)
```

```{r}
spread_duration<- merge(xts_a_oas,xts_a_dur,xts_bbb_oas,xts_bbb_dur)
```

```{r}
spread_duration$a_oas_dur<- spread_duration$xts_a_oas/spread_duration$xts_a_dur
spread_duration$bbb_oas_dur<- spread_duration$xts_bbb_oas/spread_duration$xts_bbb_dur
spread_duration$spread_per_dur<- spread_duration$bbb_oas_dur - spread_duration$a_oas_dur
```

```{r}
plot(spread_duration$xts_bbb_dur, col = "red", main = "BBB Duration")
plot(spread_duration$xts_a_dur, col = "red", main = "A Duration")
plot(spread_duration$xts_bbb_oas, col = "red", main = "BBB OAS")
plot(spread_duration$xts_a_oas, col = "red", main = "A OAS")
plot(spread_duration$bbb_oas_dur, col = "red", main = "BBB Spread per unit of Duration")
plot(spread_duration$a_oas_dur, col = "red", main = "A Spread per unit of Duration")
plot(spread_duration$spread_per_dur, col = "red", main = "BBB Spread per unit of Duration Less A Spread per unit of Duration")
```

```{r}
boxplot(coredata(spread_duration$spread_per_dur, col = "wheat", horizontal = TRUE, main = "BBB SPUD less A SPUD / red dash = current, green = mean", tick = TRUE, cex.axis = 0.5))
axis(1, at=seq(-0.12,0.45,0.025), cex.axis = 0.5)
#abline(v = last(coredata(spread_duration$spread_per_dur), col = "red", lwd = 2, lty = 2))
#abline(v = mean(coredata(spread_duration$spread_per_dur), col = "green", lwd = 2))
```

```{r}
long_er_xts<- xts(long_er[,-1], order.by = long_er$date)
crv530_xts<- xts(crv530[,-1], order.by = crv530$date)
us_30yr_xts<- xts(us_30yr[,-1], order.by = us_30yr$date)
long_er_crv<- merge(long_er_xts,crv530_xts, us_30yr_xts)
long_er_crv$crv_diff<- diff(long_er_crv,1)
long_er_crv$er_bps<- long_er_crv$long_er_xts * 100
long_er_crv$us_30_diff<- diff(long_er_crv$us_30yr_xts,1)
```

```{r}
ggplot(as.data.frame(long_er_crv), aes(crv_diff, er_bps)) + geom_point() + geom_smooth(method = 'lm')
```
```{r}
ggplot(as.data.frame(long_er_crv), aes(us_30_diff, er_bps)) + geom_point() + geom_smooth(method = 'lm') + theme_minimal() + ggtitle('Monthly long credit excess returns versus change in 30yr yields')
```
```{r}
##Experimenting with daily tick data (Bloomberg will only give intraday data from prior six months)
security<- "USGG3OYR INDEX"
eventType<- "ASK"
startTime<- as.POSIXct("2020-12-10 12:59:59")
endTime<- as.POSIXct("2020-12-10 13:00:00")
```

```{r}
getTicks(security = "USGG30YR INDEX", eventType = eventType, startTime = startTime, endTime = endTime, tz = "EST")
```
```{r}
##Convert corporate OAS and MBS OAS to time series
corp_xts <- xts(corp_oas[-1], order.by = corp_oas$date)
mbs_xts <- xts(mbs_oas[-1], order.by = mbs_oas$date)
corp_mbs<- merge(corp_xts,mbs_xts)
```

```{r}
plot(corp_mbs$PX_LAST, main = "Corporate Spreads vs. MBS Spreads", col = "#FFCC33", lwd = 2, ylim = c(-0.2,7))
lines(corp_mbs$PX_LAST.1, col = "#3366CC", lwd = 2)
addLegend(legend.loc = "topright", legend.names = c("Corporate","MBS"),  ncol = 1,  fill = c("#FFCC33","#3366CC"))
```
```{r}
chi_xts<- xts(chi_fcon[-1], order.by = chi_fcon$date)
chi_adj_xts<- xts(chi_adj[-1], order.by = chi_adj$date)
bloom_xts<- xts(bloom_fcon[-1], order.by = bloom_fcon$date)
fcons<- merge(chi_xts,chi_adj_xts,bloom_xts)
colnames(fcons)[1]<- "Chicago_FCON"
colnames(fcons)[2]<- "Adjusted_Chicago_FCON"
colnames(fcons)[3]<- "Bloomberg_FCON"
```

```{r}
plot(fcons$Chicago_FCON, main = "FRB Chicago Financial Conditions", col = "#FFCC33", lwd = 2, ylim = c(-2,4))
lines(fcons$Adjusted_Chicago_FCON, col = "#3366CC", lwd = 2)
addLegend(legend.loc = "topright", legend.names = c("Financial Conditions","Adjusted Financial Conditions"),  ncol = 1,  fill = c("#FFCC33","#3366CC"))
```
```{r}
plot(fcons$Bloomberg_FCON, main = "Bloomberg Financial Conditions", col = "#FFCC33", lwd = 2, ylim = c(-10,2))
addLegend(legend.loc = "topright", legend.names = ("Bloomberg Financial Conditions"),  ncol = 1,  fill = ("#FFCC33"))
```



```{r}
test<- bloom(c("SPX INDEX", "LUACOAS INDEX"), "PX_LAST", start_date,FALSE)
```

