---
title: "Recession Indicators"
author: "Andrew"
date: "2022-10-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
##load packages
library(ggplot2)
library(zoo)
library(quantmod)
library(roll)
library(Rblpapi)
library(TTR)
library(tis)
con<- blpConnect()
start_date <- as.Date("2007-10-01")
non_trade <- "FALSE"
```


```{r}
##Retrieve yield curve data from Fred for the 10yr Constant Maturity Yield less the Fed Funds Rate (daily series)
ten_ffr<- getSymbols("T10YFF", src = "FRED", auto.assign = FALSE)
```

```{r}
##Retrieve NBER Recession dates, 0 = no recession, 1 = recession (monthly series)
recess<- getSymbols("USREC", src = "FRED", auto.assign = FALSE)
```

```{r}
#Merge ten_ffr and recess, start data at 1962-01-02, carry forward the monthly recession indicators to each day within month
recess_df<- merge(ten_ffr, recess)
recess_df<- recess_df["1962/"]
recess_df<- na.locf(recess_df)
```

```{r}
##Create new variable indicating if economy in recession 12 months out (pull the recession indicator variable 265 working days into the past)
recess_df$lead_recess<- stats::lag(recess_df$USREC,-265)
```

```{r}
##Create dataframe on monthly time periods, truncate dataframe to the start of curve data
ten_ffr_monthly<- to.monthly(ten_ffr)
recess_monthly<- merge(recess, ten_ffr_monthly)
recess_monthly<- recess_monthly["1962/"]
recess_monthly<- na.locf(recess_monthly)
recess_monthly$lead_recess<- stats:: lag(recess_monthly$USREC,-12)
```


```{r}
##Plot of 10yr less FFR curve spread for all time periods
plot(recess_df$T10YFF, main = "10yr UST Yield less FFR", col = "#FFCC33", ylim = c(-12,6), lwd = 0.5)
```

```{r}
##Plot of monthly 10yr less FFR Curve (Monthly data)
plot(recess_monthly$ten_ffr.Open, main = "10yr UST Yield less FFR", col = "#FFCC33")
```


```{r}
##Plot of 10yr less FFR curve spread for 1997 to present
plot(recess_df$T10YFF["1997/"], main = "10yr UST Yield less FFR", col = "#FFCC33")
```

```{r}
#Split into training and test datasets (5 recessions in training set and 3 recessions in test set)
train_recess<- window(recess_df["/12-31-1996"])
test_recess<- window(recess_df["1997-01-01/"])
```

```{r}
#Split into training and test datasets for monthly data
monthly_train<- window(recess_monthly["/1997"])
monthly_test<- window(recess_monthly["1997/"])
```


```{r}
##First Logistic regression model for the data
rec_glm<- glm(lead_recess ~ T10YFF, data = train_recess, family = binomial(link = "logit"))
summary(rec_glm)
```

```{r}
rec_glm_monthly<- glm(lead_recess ~ ten_ffr.Open, data = monthly_train, family = binomial(link = "logit"))
summary(rec_glm_monthly)
```

```{r}
#Function to convert log odds to probability
logit_prob<- function(logit){
  odds<- exp(logit)
  prob<- odds / (1 + odds)
  return(prob)
}
```


```{r}
#Augment training data to get log odds of recess based on fitted model, convert to probabilities, and convert to xts
library(broom)
aug_glm_mon<- augment(rec_glm_monthly)
aug_glm_mon$probs<- logit_prob(aug_glm_mon$.fitted)
aug_glm_xts<- xts(aug_glm_mon[,-1], order.by = as.Date(aug_glm_mon$.rownames, "%Y-%m-%d"))
```

```{r}
#Plot of training data model fitted probs
plot(aug_glm_xts$probs, main = "Probability of Recession: 10yr/FFR Spread - Train Data", col = "#FFCC33")
```



```{r}
##Using fitted model to predict on test set, response output of probabilities from model
recess_predict<- predict(rec_glm,test_recess, type = "response")
summary(recess_predict)
```
#Predicted recession probabilities range from nearly 0% upwards to 44.2%.  Average probability over entire timeframe was around 7.2% with the median at 4.8%.  

```{r}
##Create dataframe of predicted probabilites, convert to xts, and change column name
rec_pred_df<- as.data.frame(recess_predict)
rec_pred_df$date<- as.Date(rownames(rec_pred_df),"%Y-%m-%d")
rec_prob_xts<- xts(rec_pred_df[,-2], order.by = rec_pred_df$date)
colnames(rec_prob_xts)[1]<- "Probability"
```

```{r}
##Plot of recession probabilities
plot(rec_prob_xts$Probability, main = "Probability of Recession: 10yr/FFR Spread", col = "#FFCC33")
```

```{r}
##Using fitted model to predict on test set, response output of probabilities from model (MONTHLY DATA)
recess_predict_monthly<- predict(rec_glm_monthly,monthly_test, type = "response")
summary(recess_predict_monthly)
```

```{r}
##Create dataframe of predicted probabilites, convert to xts, and change column name (MONTHLY DATA)
rec_pred_df_mon<- as.data.frame(recess_predict_monthly)
rec_pred_df_mon$date<- as.Date(rownames(rec_pred_df_mon),"%Y-%m-%d")
rec_prob_xts_mon<- xts(rec_pred_df_mon[,-2], order.by = rec_pred_df_mon$date)
colnames(rec_prob_xts_mon)[1]<- "Probability"
```

```{r}
##Plot of recession probabilities (MONTHLY DATA)
plot(rec_prob_xts_mon$Probability, main = "Probability of Recession: 10yr/FFR Spread", col = "#FFCC33")
```


```{r,echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#Load the tsbox package and convert the rec xts dataframe into a time series object
library(tsbox)
rec_ts<- ts_ts(rec_prob_xts)
rec_ts_mon<- ts_ts(rec_prob_xts_mon)
aug_ts<- ts_ts(aug_glm_xts$probs)
```

```{r,echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#Plot the rec time series object and add recession shading using nberShade
plot(rec_ts, type = 'n', main = "Recession Probability", ylab = "Probability", xlab = "Date")
nberShade()
lines(rec_ts, col = "#FFCC33", lwd = 2)
abline(h=0.11, lty = 2, col = "#3366CC")
```

```{r,echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#Plot the Sahm time series object and add recession shading using nberShade (MONTHLY DATA)
plot(rec_ts_mon, type = 'n', main = "Recession Probability - Monthly", ylab = "Probability", xlab = "Date")
nberShade()
lines(rec_ts_mon, col = "#FFCC33", lwd = 2)
abline(h=0.11, lty = 2, col = "#3366CC")
```

```{r,echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#Plot the recession probs time series object and add recession shading using nberShade
plot(aug_ts, type = 'n', main = "Recession Probability", ylab = "Probability", xlab = "Date")
nberShade()
lines(aug_ts, col = "#FFCC33", lwd = 2)
abline(h=0.11, lty = 2, col = "#3366CC")
```

```{r}
library(pROC)
roc(as.matrix(test_recess$lead_recess),round(recess_predict))
```

```{r}
##Setting threshold probability for the model and looking at the confusion matrix (Actual on side, predicted across top of matrix)
thresh<- 0.3
rec_predict_thresh<- as.integer(recess_predict> thresh)
(conf_matrix<- as.matrix(table(test_recess$lead_recess, rec_predict_thresh)))
```

```{r}
##Creating a vector of thresholds. The models predicted values range from 0.006 to 0.442
thresh_seq<- seq(0.01,0.40,0.05)
```

```{r}
##Creating function to compare several threshold levels in the model
thresh_func<- function(x){
  pt<- as.integer(recess_predict>x)
  return(pt)
}
```

```{r}
##Applying threshold function across vector of thresholds
thresholds<-lapply(thresh_seq, thresh_func)
```


```{r}
##Function to create confusion matrices across all thresholds
cm_func<- function(y){
  mtx<- as.matrix(table(test_recess$lead_recess,y))
  return(mtx)
}
```

```{r}
##Applying confusion matrix function to see confusion matrix for each threshold 
(thresh_mtx<- lapply(thresholds,cm_func))
```

```{r}
#Create an accuracy function to apply to each threshold matrix
accuracy<- function(x){
  acc<- (x[1,1] + x[2,2])/sum(x)
  return(acc)
}
```

```{r}
#Create a Sensitivity function to apply to each threshold matrix (calculates percent of predicting true positives to all true positives and negatives)
sensitivity<- function(x){
  sens<- (x[1,1]/(x[1,1] + x[1,2]))
  return(sens)
}
```

```{r}
#Create a Specificity function to apply to each threshold matrix (calculates percent of predicting true negatives to sum of true positives and false positives)
specificity<- function(x){
  spec<- (x[2,2]/(x[2,2] + x[2,1]))
  return(spec)
}
```


```{r}
#Calculate the accuracy of each matrix
(result<- lapply(thresh_mtx, accuracy))
acc_df<- t(as.data.frame(result,col.names = thresh_seq))
acc_df <- cbind(newColName = rownames(acc_df), acc_df)
rownames(acc_df) <- 1:nrow(acc_df)
```

```{r}
#Calculate the sensitivity of each matrix (True positive rate)
(result_sens<- lapply(thresh_mtx, sensitivity))
acc_df_sens<- t(as.data.frame(result_sens,col.names = thresh_seq))
acc_df_sens <- cbind(newColName = rownames(acc_df_sens), acc_df_sens)
rownames(acc_df_sens) <- 1:nrow(acc_df_sens)
```

```{r}
#Calculate the specificity of each matrix (True Negative Rate)
(result_spec<- lapply(thresh_mtx, specificity))
acc_df_spec<- t(as.data.frame(result_spec,col.names = thresh_seq))
acc_df_spec <- cbind(newColName = rownames(acc_df_spec), acc_df_spec)
rownames(acc_df_spec) <- 1:nrow(acc_df_spec)
```


```{r}
library(kableExtra)
#Create fancy table of accuracy level at each threshold
kable(acc_df, col.names = c("Threshold Level","Model Accuracy"))
```



```{r}
#Create fancy table of sensitivity level at each threshold
kable(acc_df_sens, col.names = c("Threshold Level","Model Sensitivity"))
```

```{r}
#Create fancy table of specificty level at each threshold
kable(acc_df_spec, col.names = c("Threshold Level","Model Specificity"))
```

```{r}
library(EWS)
clean_recess<- recess_df["1962-01-02/2021-10-19"]
y<- as.vector(clean_recess$lead_recess)
x<- as.vector(clean_recess$T10YFF)
ews_model<- Logistic_Estimation(Dicho_Y = y,Exp_X =  x, Intercept = TRUE, Nb_Id = 1, Lag = 1, type_model = 1)
```

```{r}
ews_model
```
```{r}
test_2<- window(recess_df["2021-10-20/"])
predict(ews_model,test_2)
```


